### PR TITLE
Update members-list.json

### PR DESCRIPTION
**Pull request by banaan666**

### CODE REVIEW

**Comment by edwinm** [comment]
A formatted JSON is really preferred.

**Review by edwinm — APPROVED** [review]

**Comment by SleeplessByte** [comment]
@edwinm then why was this merged 😆 ?

**Comment by banaan666** [comment]
Because this is how we currently update the memberlist, it was never formatted before. Also I don't have the time and energy currently to look into adding formatting to the JSON I export from the membership administration.

**Comment by banaan666** [comment]
That would be really helpful Derk-Jan if you could implement this on the Github side of things.

**Comment by SleeplessByte** [comment]
I'll add it to my list!

**Pull request merged**
